import os
import requests
from flask import Flask, redirect, request, session, render_template_string
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
app.secret_key = os.urandom(24)

# Environment variables
CLIENT_ID = os.getenv("AZURE_CLIENT_ID")
CLIENT_SECRET = os.getenv("AZURE_CLIENT_SECRET")
TENANT_ID = os.getenv("AZURE_TENANT_ID")
GCP_URL = os.getenv("GCP_BACKEND_URL")
# The redirect URI will be the EC2 public DNS
REDIRECT_URI = os.getenv("REDIRECT_URI") 

AUTHORITY = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0"

@app.route("/")
def index():
    if "id_token" in session:
        return f"""
        <h3>Authenticated!</h3>
        <p>Your Azure ID Token has been stored.</p>
        <form action="/call-gcp" method="post">
            <button type="submit">Send Token to GCP Backend</button>
        </form>
        """
    return '<a href="/login">Login with Azure Entra ID</a>'

@app.route("/login")
def login():
    auth_url = f"{AUTHORITY}/authorize?client_id={CLIENT_ID}&response_type=code&redirect_uri={REDIRECT_URI}&response_mode=query&scope=openid profile email"
    return redirect(auth_url)

@app.route("/callback")
def callback():
    code = request.args.get("code")
    if not code:
        return "Authentication failed."
    
    # Exchange code for token
    token_data = {
        "client_id": CLIENT_ID,
        "scope": "openid profile email",
        "code": code,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code",
        "client_secret": CLIENT_SECRET,
    }
    token_r = requests.post(f"{AUTHORITY}/token", data=token_data)
    session["id_token"] = token_r.json().get("id_token") # Save ID token to pass to GCP
    return redirect("/")

@app.route("/call-gcp", methods=["POST"])
def call_gcp():
    id_token = session.get("id_token")
    headers = {"Authorization": f"Bearer {id_token}"}
    
    try:
        # Call the GCP backend
        response = requests.post(GCP_URL, headers=headers, verify=False)
        return f"<h3>GCP Backend Response:</h3><p>{response.text}</p><a href='/'>Go Back</a>"
    except Exception as e:
        return f"Error connecting to GCP: {str(e)}"

if __name__ == "__main__":
    # Run using the self-signed certs generated by the EC2 User Data script
    app.run(host="0.0.0.0", port=443, ssl_context=('/home/ubuntu/cert.pem', '/home/ubuntu/key.pem'))
